name: CI

on:
  pull_request:
    branches:
    - "*"

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --no-plugins
    - name: Run PHP CS Fixer
      run: composer phpcs

  tests:
    runs-on: ubuntu-latest
    needs: [codestyle]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --no-plugins
    - name: Run PHPUnit
      run: composer test
